### PR TITLE
Fix debug security issue by upgrading

### PR DESCRIPTION
**Pull request by madarche**
cf. https://nodesecurity.io/advisories/534

Cheers

### CODE REVIEW

**Comment by madarche** [comment]
@dougwilson the Travis CI build fails, but it is due to the upgrade of supertest to supertest@3.0.0 that you've done earlier.

**Comment by dougwilson** [comment]
Are you using the beta version or the stable version of this module?

**Comment by madarche** [comment]
I was using cookie-session@2.0.0-alpha.x and then  cookie-session@2.0.0-beta.x for some time. Then the security warning on cookie-session made me write this PR.

Since this PR I've switched to cookie-session@1.3.2 that fixes the security issue. But I was thinking that you, and possibly others, might appreciate the PR. On my side there is no problem anymore.

If this PR causes trouble/is not aligned with your plans, don't hesitate to close it.

Cheers and thanks for all the express!

**Comment by dougwilson** [comment]
No, the PR is fine. I was just checking because a lot of modules that use debug 2.x that have been upgraded to 2.6.9 are still getting issues opened incorrectly, so just wanted to validate. The beta of this module needs to be updated, but wanted to make sure what you expected to see matched what would happen :)

**Comment by madarche** [comment]
Fine 😄 And yes I've read the issues opened wrongly that you are referring to. I've used all the express related packages that you have published lately wrt to the debug package and not found any problem in one of them.

**Pull request closed without merging**
