### PR TITLE
Bump 'cookies' to 0.8.0

### PR DESCRIPTION
**Pull request by aspett**
Related to (and may close) #131

### CODE REVIEW

**Comment by feathj** [comment]
We need this dependency bump as well. Thanks.

**Comment by feathj** [comment]
We probably want to change the readme to include the `none` option for `sameSite`

**Comment by aspett** [comment]
Good suggestion @feathj. Hopefully one of the contributors will pick this up shortly.

**Comment by aspett** [comment]
@dougwilson Perhaps?

**Comment by mochtu** [comment]
+1 needed soon to support chrome.

**Comment by dobbym** [comment]
The Chrome 80 samesite change is due imminently. Will this be merged soon?

**Comment by flipvh** [comment]
Also waiting for the PR to be merged. Is something wrong? Thanks in advance!

**Comment by dougwilson** [comment]
Hi all, sorry about this. I see this PR is updating the beta version. Are you guys using the beta 2 or the stable 1?

**Comment by aspett** [comment]
> 
> 
> Hi all, sorry about this. I see this PR is updating the beta version. Are you guys using the beta 2 or the stable 1?

Not sure what you're referring to, sorry?

**Comment by dougwilson** [comment]
What version of this module are you planning to use this update on?

**Comment by aspett** [comment]
Oh, gotcha. We were using the beta previously.

**Comment by dougwilson** [comment]
Ok. Yea, this PR is just for the beta. The question was mainly for all the people who keep asking when it will land. I assumed you made the PR for what you need. Just want to make sure everyone has the same expectation for what this PR will appear on npm as.

**Comment by flipvh** [comment]
We are using the beta too

**Comment by flipvh** [comment]
Hi @dougwilson , is there something that can be done to merge this? Or is there a reason for keeping this pull request open? Our customers doing checks with the new Chrome browser and asking us why we still haven't configured properly to deal with `samesite` functionality

**Comment by dobbym** [comment]
@flipvh The latest version of cookie-session uses cookies 0.8.0.

**Comment by dougwilson** [comment]
Sorry, this doesn't merge due to merge conflicts that were created when I merged the 1.x changes into master. Resolving the conflicts just make the PR have to changes, my bad. It should be closed as "merged" since the changes are on the targeted branch.

As @dobbym noted cookies 0.8.0 is available is the current version. The "next" version (the 2.0 beta) I will publish soon as rc.1 with the final changes for that version to validate before promoting to 2.0.

**Pull request closed without merging**
