### PR TITLE
Change the maxage for a specific session

### PR DESCRIPTION
**Pull request by andreax79**
Sorry some problems in merging, I hope this is correct

### CODE REVIEW

**Comment by maxhoffmann** [comment]
any update on this?

**Comment by maxhoffmann** [comment]
@dougwilson I know there is a lot to do as an open source contributor, but I would be very happy if you could merge this pull request. And the users of the site I’m working on, too. :)

**Comment by dougwilson** [comment]
Yea, yea, I'm sorry :( I'll try my best to do this today. Still getting up to speed on this module and I can't merge this until there are tests, so just need to find time to write tests that go along with this unless someone can before me.

**Comment by tgriesser** [comment]
Looks like there's a test here - https://github.com/andreax79/cookie-session/pull/1

**Comment by dougwilson** [comment]
Can someone explain why you cannot use `req.sessionOptions.maxAge = newMaxAge`?

**Comment by dougwilson** [comment]
Eh, nevermind. That doesn't work right. This module needs a serious overhaul :)

**Comment by dougwilson** [comment]
For now, with version 1.2.0, the solution would be as follows if you want a sticky maxAge:
```js
app.use(cookieSession())
app.use(function (req, res, next) {
  req.sessionOptions = req.session.maxAge || req.sessionOptions
})
```

**Pull request closed without merging**
