### PR TITLE
Added version number

### PR DESCRIPTION
**Pull request by alvarotrigo**

### CODE REVIEW

**Comment by dougwilson** [comment]
No thanks, as we have to update this every release.

**Comment by alvarotrigo** [comment]
@dougwilson mmm I don't really get it.
You will update the code on every release as well. So the file will be updated in any case.

**Comment by dougwilson** [comment]
Because no other module I maintain is like that, I can pretty much guarantee you I'll never remember to update it. It's about even remembering to update it, not the mechanics of doing so.

**Comment by alvarotrigo** [comment]
I'm not very used to back-end stuff, but all front end components or plugins contain a version number.

**Comment by dougwilson** [comment]
The version number is in the package.json file, which is installed next to the index.json file.

**Pull request closed without merging**
